version: "3"
services:
    server:
        build: .
        ports:
          - 8008:8008
    mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        volumes:
          - mongodb-storage:/data/db
    web:
        image: php:8.1.7-apache
        ports:
          - 80:80
        volumes: 
          - C:\Users\phill\Desktop\stonks-web:/var/www/html/
volumes: 
  mongodb-storage: